import dash
from dash import html, dcc, Input, Output
from src.models.DashPlotlyGameRenderer import DashPlotlyGameRenderer

# Initialize the Dash app
app = dash.Dash(__name__)
app.title = "DashPlotlyGameRenderer Animation"

# Hardcoded match ID and frame range
MATCH_ID = "1886347"
START_FRAME = 0
END_FRAME = 100  # Reduced range for faster loading

def get_figures():
    """Load data using DashPlotlyGameRenderer and return the generated figures"""
    try:
        game_renderer = DashPlotlyGameRenderer(config_file='analytics_cup_analyst/src/config/simple_game_renderer_config.json')
        figures = game_renderer.plot_episode(MATCH_ID, START_FRAME, END_FRAME, delay=0)
        return figures
    except Exception as e:
        print(f"Error generating figures: {e}")
        return []

# Get the figures
figures = get_figures()

# Create layout components
def create_layout():
    if len(figures) > 0:
        return html.Div([
            html.H1("DashPlotlyGameRenderer Animation"),
            html.H2(f"Match ID: {MATCH_ID}"),
            html.H2(f"Frame Range: {START_FRAME} - {END_FRAME}"),
            html.H2(f"Total Figures: {len(figures)}"),
            html.H3(id='current-frame-info'),
            dcc.Graph(id='animated-figure'),
            dcc.Interval(
                id='animation-interval',
                interval=100,  # 0.1 seconds = 100 milliseconds
                n_intervals=0,
                max_intervals=len(figures)  # Play once through all figures
            ),
            html.P("This app animates through all figures generated by DashPlotlyGameRenderer.")
        ])
    else:
        return html.Div([
            html.H1("DashPlotlyGameRenderer Animation"),
            html.H2(f"Match ID: {MATCH_ID}"),
            html.H2(f"Frame Range: {START_FRAME} - {END_FRAME}"),
            html.H2("Error: No figures generated"),
            html.P("Unable to generate figures using DashPlotlyGameRenderer.")
        ])

# Set the layout
app.layout = create_layout()

# Callback to update the figure and frame info
@app.callback(
    [Output('animated-figure', 'figure'),
     Output('current-frame-info', 'children')],
    [Input('animation-interval', 'n_intervals')]
)
def update_figure(n_intervals):
    if len(figures) == 0:
        return {}, "No figures available"
    
    # Show figures sequentially, stop at the last one
    if n_intervals >= len(figures):
        figure_index = len(figures) - 1  # Stay on last figure
        current_figure = figures[figure_index]
        frame_info = f"Animation Complete - Frame {figure_index + 1} of {len(figures)}"
    else:
        figure_index = n_intervals
        current_figure = figures[figure_index]
        frame_info = f"Frame {figure_index + 1} of {len(figures)}"
    
    return current_figure, frame_info

if __name__ == '__main__':
    app.run(debug=True, port=8050)
