import dash
from dash import html, dcc, Input, Output, callback_context, no_update
from src.models.DashPlotlyGameRenderer import DashPlotlyGameRenderer

# Initialize the Dash app
app = dash.Dash(__name__)
app.title = "DashPlotlyGameRenderer Animation"

# Hardcoded match ID and frame range
MATCH_ID = "1886347"
START_FRAME = 0
END_FRAME = 100  # Reduced range for faster loading

def get_figures():
    """Load data using DashPlotlyGameRenderer and return the generated figures"""
    try:
        game_renderer = DashPlotlyGameRenderer(config_file='analytics_cup_analyst/src/config/simple_game_renderer_config.json')
        figures = game_renderer.plot_episode(MATCH_ID, START_FRAME, END_FRAME, delay=0)
        return figures
    except Exception as e:
        print(f"Error generating figures: {e}")
        return []

# Get the figures
figures = get_figures()

# Create layout components
def create_layout():
    if len(figures) > 0:
        return html.Div([
            html.H1("DashPlotlyGameRenderer Animation", style={'textAlign': 'center'}),
            html.H2(f"Match ID: {MATCH_ID}", style={'textAlign': 'center'}),
            html.H2(f"Frame Range: {START_FRAME} - {END_FRAME}", style={'textAlign': 'center'}),
            html.H2(f"Total Figures: {len(figures)}", style={'textAlign': 'center'}),
            html.H3(id='current-frame-info', style={'textAlign': 'center'}),
            html.Div([
                html.Button('Play', id='play-button', n_clicks=0, style={
                    'backgroundColor': '#28a745',
                    'color': 'white',
                    'border': 'none',
                    'padding': '10px 20px',
                    'margin': '10px 5px',
                    'borderRadius': '5px',
                    'cursor': 'pointer'
                }),
                html.Button('Pause', id='pause-button', n_clicks=0, style={
                    'backgroundColor': '#dc3545',
                    'color': 'white',
                    'border': 'none',
                    'padding': '10px 20px',
                    'margin': '10px 5px',
                    'borderRadius': '5px',
                    'cursor': 'pointer'
                }),
                html.Button('Reset', id='reset-button', n_clicks=0, style={
                    'backgroundColor': '#6c757d',
                    'color': 'white',
                    'border': 'none',
                    'padding': '10px 20px',
                    'margin': '10px 5px',
                    'borderRadius': '5px',
                    'cursor': 'pointer'
                })
            ], style={'textAlign': 'center'}),
            html.Div(
                children=[
                    html.Div(
                        dcc.Graph(
                            id='animated-figure',
                            style={"width": "100%", "height": "100%"},
                            #style={"width": "800px", "height": "600px"}  # fixed size works well
                        ),
                        style={
                            "flex": "0 0 auto",   # do not stretch
                        }
                    )
                ],
                style={
                    "display": "flex",
                    "justifyContent": "center",  # horizontal center
                    "alignItems": "center",      # vertical center
                }
            ),
            dcc.Interval(
                id='animation-interval',
                interval=100,  # 0.1 seconds = 100 milliseconds
                n_intervals=0,
                max_intervals=len(figures),  # Play once through all figures
                disabled=True  # Start paused
            ),
            html.P("This app animates through all figures generated by DashPlotlyGameRenderer.")
        ], style={
            'maxWidth': '1200px',
            'margin': '0 auto',
            'fontFamily': 'Arial, sans-serif'
        })
    else:
        return html.Div([
            html.H1("DashPlotlyGameRenderer Animation", style={'textAlign': 'center'}),
            html.H2(f"Match ID: {MATCH_ID}", style={'textAlign': 'center'}),
            html.H2(f"Frame Range: {START_FRAME} - {END_FRAME}", style={'textAlign': 'center'}),
            html.H2("Error: No figures generated", style={'textAlign': 'center'}),
            html.P("Unable to generate figures using DashPlotlyGameRenderer.", style={'textAlign': 'center'})
        ], style={
            'maxWidth': '1200px',
            'margin': '0 auto',
            'padding': '20px',
            'fontFamily': 'Arial, sans-serif'
        })

# Set the layout
app.layout = create_layout()

# Callback to control play/pause/reset
@app.callback(
    [Output('animation-interval', 'disabled'),
     Output('animation-interval', 'n_intervals')],
    [Input('play-button', 'n_clicks'),
     Input('pause-button', 'n_clicks'),
     Input('reset-button', 'n_clicks')],
    prevent_initial_call=True
)
def control_animation(play_clicks, pause_clicks, reset_clicks):
    ctx = callback_context
    if not ctx.triggered:
        return True, 0
    
    button_id = ctx.triggered[0]['prop_id'].split('.')[0]
    
    if button_id == 'play-button':
        return False, no_update  # Enable interval, keep current n_intervals
    elif button_id == 'pause-button':
        return True, no_update   # Disable interval, keep current n_intervals
    elif button_id == 'reset-button':
        return True, 0                # Disable interval and reset to beginning
    
    return True, 0

# Callback to update the figure and frame info
@app.callback(
    [Output('animated-figure', 'figure'),
     Output('current-frame-info', 'children')],
    [Input('animation-interval', 'n_intervals')]
)
def update_figure(n_intervals):
    if len(figures) == 0:
        return {}, "No figures available"
    
    # Show figures sequentially, stop at the last one
    if n_intervals >= len(figures):
        figure_index = len(figures) - 1  # Stay on last figure
        current_figure = figures[figure_index]
        frame_info = f"Animation Complete - Frame {figure_index + 1} of {len(figures)}"
    else:
        figure_index = n_intervals
        current_figure = figures[figure_index]
        frame_info = f"Frame {figure_index + 1} of {len(figures)}"
    
    return current_figure, frame_info

if __name__ == '__main__':
    app.run(debug=True, port=8050)
